kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod
  namespace: nginx-ns
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"

